export const SET_CATALOG = 'SET_CATALOG';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const SET_PAGINATED_PRODUCTS = 'SET_PAGINATED_PRODUCTS'; 
